### PR TITLE
Support ghc-events-0.13

### PR DESCRIPTION
**Pull request by maoe**
This PR updates the library to support the new Text based API in ghc-events.

I've tested this PR with some eventlogs but haven't tested the scripting feature because I don't know how to use it.

String is still used in a few places:

* GHC.RTS.Events.Analyze.Reports.Timed.SVG: The underlying library exposes only String-based API
* GHC.RTS.Events.Analyze.Script: parsec doesn't provide Text.Parsec.Language for Text (https://github.com/haskell/parsec/issues/55)
* Text.Print.printf: Only available for String

### CODE REVIEW

**Comment by edsko** [comment]
Sorry for the slow reply. I just tried building this, but it doesn't compile for me; 

```
src/GHC/RTS/Events/Analyze/Script.hs:276:3: error:
    • No instance for (Lift EventLabel) arising from a use of ‘lift’
```

Do you have any local changes that aren't part of this PR maybe?

**Comment by maoe** [comment]
What version of GHC are you using? 8.8.4 builds fine for me. Also I have no uncommitted changes.

**Comment by maoe** [comment]
Reproduced the error with GHC 8.10.2. Pushed a fix.

**Comment by edsko** [comment]
Ok, that worked, thanks!

**Comment by edsko** [comment]
This is now released :)

**Pull request merged**
