### PR TITLE
Add support for GHC 7.10

### PR DESCRIPTION
**Pull request by WillSewell**
Let me know if you have any feedback :)

### CODE REVIEW

**Comment by edsko** [comment]
Oh, wow, you even made it compatible with diagrams 1.2 and diagrams 1.3. Looks good. Merging with thanks! I noticed that it doesn't compile with 7.8 but I also noticed that this isn't the fault of this PR :) Will fix that separately.

**Comment by edsko** [comment]
@WillSewell Ok, fixed the compilation issues with 7.8 separately. Do you consider this in a good state for a new Hackage release?

**Comment by WillSewell** [comment]
Great! Yeah it was more fiddly to port over than I expected it to be.

Thanks for fixing the TH bounds. Is there a reason there was no explicit `template-haskell` bounds in `ghc-events-analyze.cabal`?

I consider it in a good state now then if it seems to be working on 7.8 and 7.10. I was using the 7.10 build yesterday with no issues.

**Comment by edsko** [comment]
Ok, released. Re TH bounds, I usually leave them unspecified as they are compiler dictated.

**Comment by WillSewell** [comment]
Thanks!

That makes sense.

**Pull request merged**
